name: Build distributable and production files

permissions:
  contents: write

env:
  PROJECT_NAME: entree
  MAKE_DEFAULT: false
  MAKE_PDF: true
  MAKE_PROD: false
  MAKE_REF: false

on:
  workflow_dispatch:
  push:
    tags: r**

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tuna-f1sh/kicad-makefile:latest
      # mount the workspace path to container workdir /project so accessible by all steps
      volumes:
        - ${{ github.workspace }}:/project

    steps:
      - uses: actions/checkout@v3

      - name: Prepare
        # https://github.com/actions/runner/issues/2033
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Run make
        if: ${{ env.MAKE_DEFAULT }}
        run: make

      - name: Run make pdf
        if: ${{ env.MAKE_PDF }}
        # merged pdf
        run: make pdf

      - name: Run make prod-*
        if: ${{ env.MAKE_PROD }}
        run: |
          # separated as most suppliers ask for this
          make prod-gerbers
          make prod-bom
          make prod-pos

      - name: Run make dist-ref
        if: ${{ env.MAKE_REF }}
        run: |
          # pcb and sch renders
          make dist-ref

      - name: Upload outputs
        uses: actions/upload-artifact@v3
        with:
          name: kicad-makefile-output
          path: output

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')

    steps:
      - name: Download outputs
        uses: actions/download-artifact@v3
        with:
          name: kicad-makefile-output
          path: output

      - name: Publish GitHub release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: false
          files: |
            output/*.pdf
            output/**/*.zip
